### ISSUE TITLE
Question: Time to reload after change on a client file

### ISSUE THREAD

**Issue by jmaguirrei** [ffxsam/ffx-meteor-react-boilerplate#11]
Hello

Yesterday I moved my project to Meteor 1.3 (I was already in 1.3 but beta.8 release) and my reload time went very bad (around 1 minute). Before that, it was seconds... I am on windows.

So, I downloaded this and try it again, this time with only 1 component (Home.js)! The time was 57 seconds after change 'Home' to 'Hello'.... Still very bad...

Do you have any idea how can I track this? On your machine how much time takes to refresh the browser after saving a file?

Thanks

**Comment by tastemeru** [comment]
Highly recommend having a look on this https://github.com/gadicc/meteor-react-hotloader

**Comment by jmaguirrei** [comment]
Yes, I am actually looking at this boilterplate project already in 1.3:

[https://github.com/thereactivestack/kickstart-meteor-react](url)

But I was expecting Meteor 1.3 to get better in this aspect, do you highly recomend webpack because you do agree this is an issue with latest Meteor?

Thanks

**Comment by ffxsam** [comment]
Sorry I can't really help. It's not an issue with this boilerplate, so I'd suggest you open an issue [here](https://github.com/meteor/meteor/issues).

**Comment by tastemeru** [comment]
I can't say that the 1.3 is better or worse on a rebuild performance, but by default, it _took some time_ to reload and with hotloader it happens almost instantly.
