### ISSUE TITLE
the example branch does NOT work?

### ISSUE THREAD

**Issue by jbenga** [ffxsam/ffx-meteor-react-boilerplate#13]
Hi, the example branch does NOT work when I do:
$ npm run example

However, the message on the command line says: 
"echo "When you're done with the example app, run 'npm run exit' to return to the boilerplate."; git checkout example". 
So, it is running somewhere. How do I view it?

**Comment by ffxsam** [comment]
I'm going to change this to be more straightforward. It's not really running, `npm run example` and `npm run exit` are just executing `git checkout` commands.

You can do `git checkout example` to switch to the example branch, and `git checkout master` to switch back. So if you're using the example branch, you can just run the example by running meteor as you normally would.

**Comment by ffxsam** [comment]
@jbenga I've updated the boilerplate to be more straightforward with regards to the example app. Check the README.md file.
