### ISSUE TITLE
basic example ?

### ISSUE THREAD

**Issue by interfaith** [ffxsam/ffx-meteor-react-boilerplate#16]
install.js:78 Uncaught Error: Cannot find module 'react-mixin'require @ install.js:78meteorInstall.client.containers.ColorSetterContainer.jsx @ ColorSetterContainer.jsx:4fileEvaluate @ install.js:141require @ install.js:75(anonymous function) @ app.js?hash=1a174f9…:1618
router.js:347 There is no route for the path: /

**Comment by interfaith** [comment]
added missing modules lodash , react-mixin. 
earlier npm commands failed  ?

**Comment by ffxsam** [comment]
I can't replicate this, the example app is working ok for me. Make sure you:

1) Have a totally clean clone of it.
2) Run `git checkout example` and then `npm install`.

As you can see in the package.json file, lodash and react-mixin are included.
