### ISSUE TITLE
A lot of things in example should be in master?

### ISSUE THREAD

**Issue by maxkrieger** [ffxsam/ffx-meteor-react-boilerplate#24]
I'm not just talking about the folder structure which isn't being generated (routes, actions), but the generated package.json is outright missing react/redux dependencies. Isn't that necessary for a boilerplate? Working off of the example branch works fine.

**Comment by ffxsam** [comment]
The actual `package.json` that gets used is in `.scripts/package-dist.json` (it gets copied to the project root level when `npm run scaffold` is run). And Redux was removed from the boilerplate, and will eventually be removed from the example app as well.

**Comment by maxkrieger** [comment]
That's unfortunate. What exactly is the roadmap for this project, then, if not just a meteor project with a react dependency?

**Comment by ffxsam** [comment]
Why is it unfortunate? Redux is not always needed, in fact, many people overuse it. Even Redux's creator preaches this all the time. 😄 

>What exactly is the roadmap for this project, then, if not just a meteor project with a react dependency?

Well, it's a boilerplate, which is nothing more than a starting point for—in this case—Meteor/React projects. It changes over time as my own needs change, or I find ways to improve it (e.g. Jest testing was just added recently).

**Comment by maxkrieger** [comment]
I understand, was just excited to finally find an example project with thunking and routing built for meteor 👍

**Comment by ffxsam** [comment]
Redux is great at solving specific problems, but at first one should make sure that things like React component state and higher-order functions can't solve this problems first. Redux should be a last resort.

FlowRouter is used in this boilerplate at the moment, though I'm considering switching to React Router at some point.

**Comment by funkybunky** [comment]
@ffxsam I just converted the boilerplate to React-Router :) Hopefully I find the time in the next days to clean it up and publish it/make a PR

**Comment by ffxsam** [comment]
@funkybunky Cool, thanks! I'll take some time to look at the changes and try to understand it before I merge it into `master`.
