### ISSUE TITLE
I'm trying to integrate with ReactJS-AdminLTE

### ISSUE THREAD

**Issue by pacozaa** [ffxsam/ffx-meteor-react-boilerplate#26]
After set up your boilerplate 

1. 

then I run `meteor npm install adminlte-reactjs`

as describe in this repo

https://github.com/booleanhunter/ReactJS-AdminLTE

2. 

- then I add this line in `features/SomeFeature/components/Thing/Thing.js`

` import {InfoTile} from 'adminlte-reactjs'; `

- Add parameter under Thing class
```

  constructor(props) {
    super(props);

    this.state = {
      infotile: {
        width: 3,
        content: '',
        icon: 'fa-envelope-o',
        stats: '1410',
        subject: 'Messages',
        theme: 'bg-aqua',
      },
    };
  }
```

- Add InfoTile component [(HERE)](https://github.com/booleanhunter/ReactJS-AdminLTE/tree/master/src/components)
```

  render() {
    return <div style={styles.root}>
      <InfoTile
          width = {this.state.infotile.width}
          content = {this.state.infotile.content}
          icon = {this.state.infotile.icon}
          stats = {this.state.infotile.stats}
          subject = {this.state.infotile.subject}
          theme = {this.state.infotile.theme}
      />
      <div>
        <button
          style={styles.button}
          onClick={this.showProps}
        >
          Dump props
        </button>
      </div>
      <div>
        <button
          style={styles.button}
          onClick={this.callMethod}
        >
          Call Meteor method
        </button>
      </div>
    </div>
  }
```
but the style is not work 

![capturereac](https://cloud.githubusercontent.com/assets/3154089/23449961/3e7ca690-fe8b-11e6-832c-0652d489d2bb.JPG)

How to solve this problem?

Best Regards,

**Comment by ffxsam** [comment]
This is outside of the scope of this boilerplate (there's no issue with the boilerplate itself). But I took a quick look at the package you referenced.. it does say this in the instructions:

> Include the stylesheets for the components, similar to the widgets page

Did you include the stylesheets and icons? Their example is here:
https://github.com/booleanhunter/ReactJS-AdminLTE/blob/master/views/widgets.html

**Comment by pacozaa** [comment]
Thank you for your respond.

Sorry for report out of scope issue.

I'm looking at it.
