### ISSUE TITLE
question: What's new these days?

### ISSUE THREAD

**Issue by cpetty-Novetta** [ffxsam/ffx-meteor-react-boilerplate#27]
I've just now stumbled across this boilerplate, and it seems to be the most robust source for explaining the meteor/react/redux stack for creating apps.  

My question is since the last commit, is there anything that should be noted to those meandering into this space?  Any specific catches that haven't been implemented into the repo due to lack of time?

**Comment by ffxsam** [comment]
Sorry, but I won't be maintaining this repo any longer, since I've decided to stop building apps in Meteor. I will say that it's probably a bit out of date, but should still work.
