### ISSUE TITLE
redux example

### ISSUE THREAD

**Issue by stocksp** [ffxsam/ffx-meteor-react-boilerplate#4]
Very sad to see the example app doesn't use the new Redux you put into this boilerplate.
:(

**Comment by ffxsam** [comment]
Funny timing, Paul. I'm actually working on it as we speak!

**Comment by stocksp** [comment]
That's great news!
I took your original example and got pretty far  ...and then found inter component communication (siblings, components not near in the tree, etc) gets nasty and the light came on.
Redux!
Looking around at   'React Forms' where I was having issues (saw your comment in formsy-react ... don't think the project is being actively worked on), and found 
https://github.com/erikras/redux-form.
Ok, Redux it is .... lets try this again...
thanks for all your work!

**Comment by ffxsam** [comment]
Example app updated with Redux!

**Comment by ffxsam** [comment]
@stocksp BTW, where did you hear that formsy-react is not actively being worked on? Thanks for the tip about redux-form, I'll check it out!

**Comment by stocksp** [comment]
That's just my opinion.  The last commit was in December.  AND the original author doesn't have time.

**Comment by ffxsam** [comment]
It's usually a bad sign when the pull requests stop getting approved or even looked at. Maybe it's hit that point.
