### ISSUE TITLE
pre-redux version?

### ISSUE THREAD

**Issue by discdiver** [ffxsam/ffx-meteor-react-boilerplate#5]
This is awesome, thank you! Could you also make available the version before you added redux?

**Comment by ffxsam** [comment]
For simplicity, there will only ever be one example app that the boilerplate can switch to in the npm script. But I've gone ahead and made a branch called `pre-redux-example` here: https://github.com/ffxsam/ffx-meteor-react-boilerplate/tree/pre-redux-example

**Comment by discdiver** [comment]
Thank you!
