### ISSUE TITLE
PostCSS

### ISSUE THREAD

**Issue by jptissot** [ffxsam/ffx-meteor-react-boilerplate#9]
Hi,  Great boilerplate ! I just wanted to suggest using postcss instead of sass. I have been experimenting with it and it seems like a very solid and powerful css transformer.

TY for building this !

**Comment by ffxsam** [comment]
You're welcome! Glad you've found it useful.

With regards to PostCSS, are you talking about [this package](https://atmospherejs.com/juliancwirko/postcss)? Or just in general.

**Comment by jptissot** [comment]
Yes, I have used that package in an app and liked how easy it was to configure the various postcss plugins (using package.json)

**Comment by ffxsam** [comment]
Great! I agree, it takes all the guesswork out of vendor prefixes and such. I'll take a serious look at it.

**Comment by jptissot** [comment]
I'll also try to contribute by createing a couple scripts for windows that replicate your .sh scripts when I have some spare time :)

**Comment by ffxsam** [comment]
That would be awesome! I've had a few complaints about that but don't know how to fix it. I think the answer lies in converting the shell scripts to node scripts?
